server:
  port: 8022
  
spring:
  application:
    name: STUDENT-SERVICE 
    
Eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost     